import Image1 from 'assets/images/eventInvitation/picture1.png';
import ImgPlaceholder from 'common/components/ui/_cards/TeamMemberCard/TeamMemberAvatar.png';
import { ITeamMemberCardProps } from 'common/components/ui/_cards/TeamMemberCard/TeamMemberCard';
// TODO DELETE USELESS IMG

// TODO ADD REAL TYPE
export interface TeamMemberType extends ITeamMemberCardProps {
  avatar: string | null;
  citizenShip: string;
  email: string;
  files: string[];
  id: number;
  isAdmin?: boolean;
  isArchived: boolean;
  isGuest?: boolean;
  isInvited: boolean;
  isOnline: boolean;
  payment: number;
  paymentFormat: 'h' | 'm';
  phone: string;
  rate: number;
  residence: string;
  reward?: number;
}

export const MEMBERS: TeamMemberType[] = [
  {
    activeProjects: 2,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 1,
    isArchived: true,
    isInvited: true,
    isOnline: true,
    name: 'Jack London',
    payment: 20,
    paymentFormat: 'h',
    phone: '+7-958-830-27-82',
    rate: 5,
    residence: 'Moscow',
    reward: 1000,
    role: 'Gardener'
  },
  {
    activeProjects: 20,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 2,
    isArchived: false,
    isInvited: false,
    isOnline: true,
    name: 'London Jack',
    payment: 280,
    paymentFormat: 'm',
    phone: '+7-958-830-27-82',
    rate: 4,
    residence: 'Moscow',
    role: 'Florist'
  },
  {
    activeProjects: 12,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 3,
    isArchived: false,
    isInvited: false,
    isOnline: true,
    name: 'Jack London',
    payment: 293,
    paymentFormat: 'm',
    phone: '+7-958-830-27-82',
    rate: 4,
    residence: 'Moscow',
    role: 'Florist'
  },
  {
    activeProjects: 8,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 4,
    isArchived: false,
    isInvited: false,
    isOnline: true,
    name: 'Jack London',
    payment: 20,
    paymentFormat: 'h',
    phone: '+7-958-830-27-82',
    rate: 4,
    residence: 'Moscow',
    reward: 1200,
    role: 'Gardener'
  },
  {
    activeProjects: 5,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 5,
    isArchived: false,
    isInvited: false,
    isOnline: true,
    name: 'Jack London',
    payment: 20,
    paymentFormat: 'h',
    phone: '+7-958-830-27-82',
    rate: 4,
    residence: 'Moscow',
    role: 'Florist'
  },
  {
    activeProjects: 1,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 6,
    isArchived: false,
    isInvited: false,
    isOnline: true,
    name: 'Jack London',
    payment: 20,
    paymentFormat: 'h',
    phone: '+7-958-830-27-82',
    rate: 5,
    residence: 'Moscow',
    role: 'Gardener'
  },
  {
    activeProjects: 2,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 7,
    isArchived: false,
    isInvited: false,
    isOnline: true,
    name: 'Jack London',
    payment: 20,
    paymentFormat: 'h',
    phone: '+7-958-830-27-82',
    rate: 5,
    residence: 'Moscow',
    reward: 1400,
    role: 'Florist'
  },
  {
    activeProjects: 7,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 8,
    isArchived: false,
    isInvited: false,
    isOnline: true,
    name: 'Jack Miles',
    payment: 20,
    paymentFormat: 'h',
    phone: '+7-958-830-27-82',
    rate: 5,
    residence: 'Moscow',
    role: 'Manager'
  },
  {
    activeProjects: 2,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 9,
    isArchived: false,
    isInvited: false,
    isOnline: true,
    name: 'Flores London',
    payment: 20,
    paymentFormat: 'h',
    phone: '+7-958-830-27-82',
    rate: 5,
    residence: 'Moscow',
    reward: 30000,
    role: 'Gardener'
  },
  {
    activeProjects: 4,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 10,
    isArchived: false,
    isInvited: false,
    isOnline: true,
    name: 'Henry London',
    payment: 20,
    paymentFormat: 'h',
    phone: '+7-958-830-27-82',
    rate: 5,
    residence: 'Moscow',
    role: 'Manager'
  },
  {
    activeProjects: 9,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 11,
    isArchived: true,
    isInvited: true,
    isOnline: true,
    name: 'Jackov Londonov',
    payment: 20,
    paymentFormat: 'h',
    phone: '+7-958-830-27-82',
    rate: 5,
    residence: 'Moscow',
    role: 'Manager'
  },
  {
    activeProjects: 8,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 12,
    isArchived: false,
    isInvited: true,
    isOnline: true,
    name: 'Jack London',
    payment: 20,
    paymentFormat: 'h',
    phone: '+7-958-830-27-82',
    rate: 5,
    residence: 'Moscow',
    role: 'Gardener'
  },
  {
    activeProjects: 3,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 13,
    isArchived: false,
    isInvited: false,
    isOnline: false,
    name: 'Jack London',
    payment: 10,
    paymentFormat: 'm',
    phone: '+7-958-830-27-82',
    rate: 3,
    residence: 'Moscow',
    reward: 400,
    role: 'Manager'
  },
  {
    activeProjects: 4,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 14,
    isArchived: true,
    isInvited: false,
    isOnline: false,
    name: 'Flores London',
    payment: 209,
    paymentFormat: 'm',
    phone: '+7-958-830-27-82',
    rate: 3,
    residence: 'Moscow',
    role: 'Gardener'
  },
  {
    activeProjects: 0,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 15,
    isArchived: false,
    isInvited: false,
    isOnline: true,
    name: 'Jack London',
    payment: 20,
    paymentFormat: 'h',
    phone: '+7-958-830-27-82',
    rate: 2,
    residence: 'Moscow',
    role: 'Manager'
  },
  {
    activeProjects: 1,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 16,
    isArchived: false,
    isInvited: false,
    isOnline: true,
    name: 'Arthur London',
    payment: 20,
    paymentFormat: 'h',
    phone: '+7-958-830-27-82',
    rate: 2,
    residence: 'Moscow',
    reward: 20,
    role: 'Gardener'
  },
  {
    activeProjects: 8,
    avatar: ImgPlaceholder,
    citizenShip: 'Russia',
    email: 'someEmail@mail.ru',
    files: [Image1],
    id: 17,
    isArchived: true,
    isInvited: true,
    isOnline: false,
    name: 'Jack Arthur',
    payment: 820,
    paymentFormat: 'm',
    phone: '+7-958-830-27-82',
    rate: 2,
    residence: 'Moscow',
    role: 'Manager'
  }
];
